### ISSUE TITLE
Unable to download database

### ISSUE THREAD

**Issue by susheelbhanu** [mmdavid/FOAM#1]
Hey David, 

I'm trying to download the database but it gives me a temporarily unavailable service error every single time. 

Is it possible to host it elsewhere?

Thanks,
Susheel

**Comment by mmdavid** [comment]
Hi, 
Sorry for the late reply. As indicated in the read me the database is here: https://cbb.pnnl.gov/portal/software/FOAM.html you can find it under "HMMs". -Maude

**Comment by hhollandmoritz** [comment]
Hello Maude,

I am also trying to download the database and the new link above didn't work for me.  (503 Service Temporarily Unavailable error). Is there some other way to access the database?

Thanks!
Hannah

**Comment by mmdavid** [comment]
Hi! My apologies, we decided to move it out of github (since it's a db not a script). You can now find it here: http://files.cgrb.oregonstate.edu/David_Lab/FOAM_version1/

**Comment by hhollandmoritz** [comment]
Hi Maude,

Thanks so much! And thanks for assembling this resource for the community!

Best,
Hannah

--
Hannah Holland-Moritz
Doctoral Candidate, Fierer Lab
EBIO Department
University of Colorado Boulder
she/her pronouns
hhollandmoritz@gmail.com
http://apipetteandanopenmind.wordpress.com/
<http://www.apipetteandanopenmind.wordpress.com>
